import{a as w,S as E,i as f}from"./assets/vendor-b11e2a50.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const d of n.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function o(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(e){if(e.ep)return;e.ep=!0;const n=o(e);fetch(e.href,n)}})();const b="44903420-1183eb8cf2f9f1f8b99b46ba0",I="https://pixabay.com/api/";async function m(t,r=1,o=15){const s=`${I}?key=${b}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${o}`;try{return(await w.get(s)).data}catch{throw new Error("Network response was not ok")}}function y(t){const r=document.getElementById("gallery"),o=t.map(e=>`
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" title="${e.tags}">
          <div>
            <p>Likes: ${e.likes}</p>
            <p>Views: ${e.views}</p>
            <p>Comments: ${e.comments}</p>
            <p>Downloads: ${e.downloads}</p>
          </div>
        </a>`).join("");r.insertAdjacentHTML("beforeend",o),new E(".gallery a").refresh()}function h(){document.getElementById("loading").style.display="block"}function l(){document.getElementById("loading").style.display="none"}function L(){f.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"})}function p(t){f.error({title:"Error",message:t})}function g(){f.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})}function c(t){const r=document.getElementById("load-more");r.style.display=t?"block":"none"}let a=1,i="",u=0;document.getElementById("search-form").addEventListener("submit",async function(t){if(t.preventDefault(),i=document.getElementById("search-input").value.trim(),a=1,u=0,!i){iziToast.error({title:"Error",message:"Please enter a search query."});return}const r=document.getElementById("gallery");r.innerHTML="",c(!1);try{h();const o=await m(i,a);l(),u=o.totalHits,o.hits.length===0?L():(y(o.hits),c(!0))}catch(o){p("Something went wrong. Please try again later."),console.error("Error fetching images:",o),l()}});document.getElementById("load-more").addEventListener("click",async function(){a+=1;try{h();const t=await m(i,a);if(l(),t.hits.length===0)g(),c(!1);else{y(t.hits);const r=document.querySelectorAll(".gallery a"),o=r[r.length-1],{height:s}=o.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"}),a*15>=u&&(g(),c(!1))}}catch(t){p("Something went wrong. Please try again later."),console.error("Error fetching images:",t),l()}});
//# sourceMappingURL=commonHelpers.js.map
