import{a as E,S as I,i as d}from"./assets/vendor-56bcefdc.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&r(u)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();const b="44903420-1183eb8cf2f9f1f8b99b46ba0",L="https://pixabay.com/api/";async function h(t,o=1,n=15){const r=`${L}?key=${b}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${n}`;try{return(await E.get(r)).data}catch{throw new Error("Network response was not ok")}}let f;function y(t){const o=document.getElementById("gallery"),n=t.map(r=>`
        <a href="${r.largeImageURL}">
          <img src="${r.webformatURL}" alt="${r.tags}" title="${r.tags}">
          <div>
            <p>Likes: ${r.likes}</p>
            <p>Views: ${r.views}</p>
            <p>Comments: ${r.comments}</p>
            <p>Downloads: ${r.downloads}</p>
          </div>
        </a>`).join("");o.insertAdjacentHTML("beforeend",n),f?f.refresh():f=new I(".gallery a")}function p(){document.getElementById("loading").style.display="block"}function l(){document.getElementById("loading").style.display="none"}function B(){d.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"})}function w(t){d.error({title:"Error",message:t})}function m(){d.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})}function c(t){const o=document.getElementById("load-more");o.style.display=t?"block":"none"}let a=1,i="",g=0;document.getElementById("search-form").addEventListener("submit",async function(t){if(t.preventDefault(),i=document.getElementById("search-input").value.trim(),a=1,g=0,!i){d.error({title:"Error",message:"Please enter a search query."});return}const o=document.getElementById("gallery");o.innerHTML="",c(!1);try{p();const n=await h(i,a);l(),g=n.totalHits,n.hits.length===0?B():(y(n.hits),c(n.hits.length>=15))}catch(n){w("Something went wrong. Please try again later."),console.error("Error fetching images:",n),l()}});document.getElementById("load-more").addEventListener("click",async function(){a+=1;try{p();const t=await h(i,a);if(l(),t.hits.length===0)m(),c(!1);else{y(t.hits);const o=document.querySelectorAll(".gallery a"),n=o[o.length-1],{height:r}=n.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),(t.hits.length<15||a*15>=g)&&(m(),c(!1))}}catch(t){w("Something went wrong. Please try again later."),console.error("Error fetching images:",t),l()}});
//# sourceMappingURL=commonHelpers.js.map
